name: Spell checking
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request_target:
  issue_comment:
    types: [created]

jobs:
  spelling:
    name: Spell checking
    permissions:
      actions: write
      contents: read
      pull-requests: read
    outputs:
      followup: ${{ steps.spelling.outputs.followup }}
      internal_state_directory: ${{ steps.spelling.outputs.internal_state_directory }}
    runs-on: ubuntu-latest
    if: "contains(github.event_name, 'pull_request') || github.event_name == 'push'"
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: test-clean
      shell: bash
      run:
        cp -R . ../introspected/;
        mv ../introspected .
    - name: test-merge
      if: "contains(github.event_name, 'pull_request')"
      uses: check-spelling/checkout-merge@v0.0.0
      with:
        path: introspected
    - name: check-spelling
      if: env.MERGE_FAILED != '1'
      id: spelling
      uses: ./
      with:
        experimental_apply_changes_via_bot: 1
        suppress_push_for_open_pull_request: 1
        check_file_names: 1
        post_comment: 0
        experimental_path: introspected
        unknown_word_limit: 2

    - name: store-comment
      if: (failure() || steps.spelling.outputs.followup == 'collapse_previous_comment') && steps.spelling.outputs.internal_state_directory
      uses: actions/upload-artifact@v2
      with:
        retention-days: 1
        name: "check-spelling-comment-${{ github.run_id }}"
        path: |
          ${{ steps.spelling.outputs.internal_state_directory }}

  comment:
    name: Comment
    runs-on: ubuntu-latest
    needs: spelling
    permissions:
      contents: write
      pull-requests: write
    if: always() && (needs.spelling.result == 'failure' || needs.spelling.outputs.followup == 'collapse_previous_comment') && needs.spelling.outputs.internal_state_directory
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: set up
      run: |
        mkdir /tmp/data
    - name: retrieve-comment
      uses: actions/download-artifact@v2
      with:
        name: "check-spelling-comment-${{ github.run_id }}"
        path: /tmp/data
    - name: comment
      uses: ./
      with:
        experimental_apply_changes_via_bot: 1
        custom_task: ${{ needs.spelling.outputs.result == 'collapse_previous_comment' && 'collapse_previous_comment' || 'comment' }}
        internal_state_directory: /tmp/data

  update:
    name: Update PR
    permissions:
      actions: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        contains(github.event.comment.body, '@check-spelling-bot apply')
      }}
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: apply spelling updates
      uses: ./
      with:
        experimental_apply_changes_via_bot: 1
